namespace RegistrationPortal.Shared.InputSelectionOptions;

public static class StateOptions
{
    public static List<SelectionOption> States { get; } = new()
    {
        new SelectionOption { Value = "AL", Text = "Alabama" },
        new SelectionOption { Value = "AK", Text = "Alaska" },
        new SelectionOption { Value = "AZ", Text = "Arizona" },
        new SelectionOption { Value = "AR", Text = "Arkansas" },
        new SelectionOption { Value = "CA", Text = "California" },
        new SelectionOption { Value = "CO", Text = "Colorado" },
        new SelectionOption { Value = "CT", Text = "Connecticut" },
        new SelectionOption { Value = "DE", Text = "Delaware" },
        new SelectionOption { Value = "FL", Text = "Florida" },
        new SelectionOption { Value = "GA", Text = "Georgia" },
        new SelectionOption { Value = "HI", Text = "Hawaii" },
        new SelectionOption { Value = "ID", Text = "Idaho" },
        new SelectionOption { Value = "IL", Text = "Illinois" },
        new SelectionOption { Value = "IN", Text = "Indiana" },
        new SelectionOption { Value = "IA", Text = "Iowa" },
        new SelectionOption { Value = "KS", Text = "Kansas" },
        new SelectionOption { Value = "KY", Text = "Kentucky" },
        new SelectionOption { Value = "LA", Text = "Louisiana" },
        new SelectionOption { Value = "ME", Text = "Maine" },
        new SelectionOption { Value = "MD", Text = "Maryland" },
        new SelectionOption { Value = "MA", Text = "Massachusetts" },
        new SelectionOption { Value = "MI", Text = "Michigan" },
        new SelectionOption { Value = "MN", Text = "Minnesota" },
        new SelectionOption { Value = "MS", Text = "Mississippi" },
        new SelectionOption { Value = "MO", Text = "Missouri" },
        new SelectionOption { Value = "MT", Text = "Montana" },
        new SelectionOption { Value = "NC", Text = "North Carolina" },
        new SelectionOption { Value = "ND", Text = "North Dakota" },
        new SelectionOption { Value = "NE", Text = "Nebraska" },
        new SelectionOption { Value = "NV", Text = "Nevada" },
        new SelectionOption { Value = "NH", Text = "New Hampshire" },
        new SelectionOption { Value = "NJ", Text = "New Jersey" },
        new SelectionOption { Value = "NM", Text = "New Mexico" },
        new SelectionOption { Value = "NY", Text = "New York" },
        new SelectionOption { Value = "OH", Text = "Ohio" },
        new SelectionOption { Value = "OK", Text = "Oklahoma" },
        new SelectionOption { Value = "OR", Text = "Oregon" },
        new SelectionOption { Value = "PA", Text = "Pennsylvania" },
        new SelectionOption { Value = "RI", Text = "Rhode Island" },
        new SelectionOption { Value = "SC", Text = "South Carolina" },
        new SelectionOption { Value = "SD", Text = "South Dakota" },
        new SelectionOption { Value = "TN", Text = "Tennessee" },
        new SelectionOption { Value = "TX", Text = "Texas" },
        new SelectionOption { Value = "UT", Text = "Utah" },
        new SelectionOption { Value = "VT", Text = "Vermont" },
        new SelectionOption { Value = "VA", Text = "Virginia" },
        new SelectionOption { Value = "WA", Text = "Washington" },
        new SelectionOption { Value = "WV", Text = "West Virginia" },
        new SelectionOption { Value = "WI", Text = "Wisconsin" },
        new SelectionOption { Value = "WY", Text = "Wyoming" }
    };
}
